### ISSUE TITLE
tomcat 7/8 crashes when using the evcache with much data

### ISSUE THREAD

**Issue by shengang1978** [Netflix/EVCache#50] opened 2017-11-20 15:36 UTC
We use the evcache as the memcached client (one note). Recently, the Tomcat 7 (we upgrade to tomcat 8.5) down several times every day. I have spent much time on it. But I only find few clue in the tomcat log (there isn't hs_err_pid file. I think the jvm crashed before it wrote the log file). 

Could you help me on this issue?

1. java runtime error.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f9959e43e10, pid=15465, tid=0x00007f9829cec700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_151-b12) (build 1.8.0_151-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.151-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x81e10]2017-11-20 23:10:39.453 INFO com.netflix.evcache.EVCacheTranscoder:  Compression increased the size of [B from 136 to 151
# [ timer expired, abort... ]

2. Sometimes, tomcat crashes when the evcache reconnecting. 
Here is the log.
2017-11-20 20:58:18.970 INFO net.spy.memcached.EVCacheConnection:  Reconnecting due to exception on {QA sa=m-bp175bd9d8160bc4.memcache.rds.aliyuncs.com/10.50.117.204:11211, #Rops=0, #Wops=0, #iq=54, topRop=null, topWop=null, toWrite=0, interested=1}
java.lang.IllegalStateException: No read operation.
	at net.spy.memcached.MemcachedConnection.handleReads(MemcachedConnection.java:842)
	at net.spy.memcached.MemcachedConnection.handleReadsAndWrites(MemcachedConnection.java:732)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:697)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
	at net.spy.memcached.EVCacheConnection.run(EVCacheConnection.java:50)
2017-11-20 20:58:18.972 WARN net.spy.memcached.EVCacheConnection:  Closing, and reopening {QA sa=m-bp175bd9d8160bc4.memcache.rds.aliyuncs.com/10.50.117.204:11211, #Rops=0, #Wops=0, #iq=87, topRop=null, topWop=null, toWrite=0, interested=1}, attempt 0.

**Comment by shengang1978** [comment] 2017-11-20 15:39
I feel strange that there are much evcache comression log. It seems that the transcoder doesn't comress the data. How can we disable the com.netflix.evcache.EVCacheTranscoder since we use the protobuf as the serialization tool.

2017-11-20 20:58:17.178 INFO com.netflix.evcache.EVCacheTranscoder:  Compression increased the size of [B from 282 to 285
2017-11-20 20:58:17.254 INFO com.netflix.evcache.EVCacheTranscoder:  Compression increased the size of [B from 282 to 285
2017-11-20 20:58:18.925 INFO com.netflix.evcache.EVCacheTranscoder:  Compression increased the size of [B from 144 to 167
2017-11-20 20:58:18.930 INFO com.netflix.evcache.EVCacheTranscoder:  Compression increased the size of [B from 223 to 229

**Comment by smadappa** [comment] 2017-11-20 18:48
1. What is the evcache-client version you are using?

The reason you might be seeing connection loss is not the cause but the effect of jvm running out of memory. This happens when the jvm is under stress and we lose connection and because there are pending operations we are trying to reconnect. 

2. EVCacheTranscoder is compressing the data but what we notice after the compression is the size of the data has increased. You can set the compression threshold to higher than 120 (default) and this should go away. 

for EX: 
default.evcache.compression.threshold=1024
https://github.com/Netflix/EVCache/blob/master/evcache-client/src/main/java/com/netflix/evcache/EVCacheTranscoder.java#L15

**Comment by shengang1978** [comment] 2017-11-21 03:15
We use the evcache version 4.99.0.

I doubt that the compression may cause the problem. I'm disabling the compression and watching the result.

**Comment by smadappa** [comment] 2017-11-21 03:48
I think there was an issue with 4.99.0 with memory leak if the connection was lost. Can you please upgrade to 4.101.0 or later which has the fix for this issue?

**Comment by shengang1978** [comment] 2017-11-21 05:19
I'll upgrade to the latest one.

**Comment by shengang1978** [comment] 2018-01-02 01:12
I upgrade the evcache to 4.104 and increase the compression threshold  to 1024. The tomcat doesn't crash any more. 

Thanks

**Closed** 2018-01-02 01:13 UTC
